[pytest]
addopts = --tb=short -ra --strict-markers --basetemp=./.pytest_tmp -p no:warnings --cov
testpaths = safecopy/tests
tmp_path_retention_count = 1
tmp_path_retention_policy = all
python_files = test_*.py *_test.py
filterwarnings =
    ignore::Warning
